### ISSUE TITLE
Allow opening links in system's default browser.

### ISSUE THREAD

**Issue by grvrulz** [artemanufrij/webpin#10]
What it says in the title. The app should allow opening external links in the system's default browser instead of opening in the sliding thing inside the app itself.

**Comment by artemanufrij** [comment]
@grvrulz could you test master branch for external link behavior, please?

**Comment by grvrulz** [comment]
It works when it recognizes external links. Sometimes it fails to recognize that a link is to another site.

For example I added a web-app for https://grv.rocks for testing, and it failed to recognize some external links there.(But I think that should be another bug, after more testing)

**Comment by artemanufrij** [comment]
@grvrulz thank you for your support!
