### ISSUE TITLE
Use blink instead of WebKitGTK?

### ISSUE THREAD

**Issue by pedrofleck** [artemanufrij/webpin#120]
Is it possible to use Blink (from Chromium) instead of WebKit in the future? Specially because elementary 5.0 uses the older WebKitGTK 2.4.11 (the latest stable is 2.26.2). The reason for this would be stability (I've got a few crashes using both Epiphany and Webpin), speed and, most of all, compatibility: Twitter videos are very buggy and most of the time won't even play, WhatsApp Web (probably the most used webapp here in Brazil, at least with people I know) isn't working and other sites have compatibility issues and slowdowns.

**Comment by sempasha** [comment]
May be related with #75 (Ability to create a web-app for the installed browser)

**Comment by janxkoci** [comment]
> elementary 5.0 uses the older WebKitGTK 2.4.11 (the latest stable is 2.26.2)

This is not true, I have 2.26.4 now. Using only default repos.

**Comment by cassidyjames** [comment]
@pedrofleck Blink is not made available as a GTK widget, so it can't be used inside of GTK apps without first writing that integration, then compiling all of Chromium with it. It would be a monumental amount of work. As @janxkoci mentioned, newer WebKit has been backported to Ubuntu 18.04 LTS and thus elementary OS 5.x.

**Comment by janxkoci** [comment]
FYI these are the webapps I currently use in Webpin and they all work fine. I only had issues with Facebook Mobile (m.facebook.com) so I create that one in Epiphany instead, where it works well (and having links open as a new tab in the same window is a plus for FB).

![Snímek z 2020-06-30 09-39-45](https://user-images.githubusercontent.com/19331850/86097905-a945eb00-bab5-11ea-9611-95c0b197f69f.png)

There were issues with Whatsapp #9 #19 before, but they were resolved in WebKitGTK itself.

**Comment by pedrofleck** [comment]
Yeah, it really is working fine for quite some time. The only problem is that WhatsApp doesn't support sending voice messages and calls outside of Chrome, but that's not a big deal for me!

**Comment by janxkoci** [comment]
> WhatsApp doesn't support sending voice messages and calls outside of Chrome

FIY: WhatsApp web is telling me this should work in Chrome, Firefox and Opera. Note that even Safari (_the_ Webkit browser) doesn't support this.

**Comment by pedrofleck** [comment]
> FIY: WhatsApp web is telling me this should work in Chrome, Firefox and Opera. Note that even Safari (_the_ Webkit browser) doesn't support this.
Yeah, and it keeps a suggestion to install WhatsApp for Mac when there's no conversation open and on my phone it looks like I connected on macOS. But, again, not a big deal and definitely not to blame on WebKit or WebPin.

**Comment by janxkoci** [comment]
That's actually to "blame" on webkit, but that's a long story 😅

**Comment by pedrofleck** [comment]
> Edit: if you are interested in the story, you can start with the comment about user agent under [this post](https://blogs.gnome.org/mcatanzaro/2019/06/14/an-openjpeg-surprise/), by Michael Catanzaro (the developer and maintainer of Epiphany browser and contributor to WebKitGTK).

What a nightmare, I didn't know it was this bad. Thanks for the link, it was an interesting read.
