### ISSUE TITLE
notify if webpin fired external request

### ISSUE THREAD

**Issue by artemanufrij** [artemanufrij/webpin#14]
@arshubham what do you think about this notification:
![external request](https://user-images.githubusercontent.com/16517095/29210749-497c6244-7e95-11e7-9a3c-c70224561f2f.png)

**Comment by arshubham** [comment]
Notification is fine. However the user must have control over weather to open the application or not like in chrome where the alert box asks for the user permission to open external links. There can be a checkbox in there such that it never shows the notification for a particular protocol.

**Comment by artemanufrij** [comment]
I'm going ot close this issue. We need a separate issue for properties/notification etc.
