### ISSUE TITLE
Add ability to copy link of the current page.

### ISSUE THREAD

**Issue by arshubham** [artemanufrij/webpin#16]
A link icon on the header bar which copies the link of the current page with a click (with toast for successful copy) would be great.

**Comment by artemanufrij** [comment]
hey @arshubham could you test current master branch please?

![bildschirmfoto von 2017-10-15 19 25 47](https://user-images.githubusercontent.com/16517095/31587261-e167539e-b1de-11e7-8459-62f352637c7a.png)

**Comment by arshubham** [comment]
Works great. However I have a few suggestions.
1. The icon looks more like for copying a file rather than a link . Maybe something like attachment icon (see GitHub editor) or Copy link icon used in Firefox 57+ page action menu.
2. A link copy feedback similar to used in firefox 57+

**Comment by artemanufrij** [comment]
@arshubham look into `/usr/share/icons/elementary/actions/symbolic/` which icon do you mean?

**Comment by arshubham** [comment]
insert-link-symbolic.svg

**Comment by artemanufrij** [comment]
done

**Comment by artemanufrij** [comment]
I would implement feedback like "external link" but auto close is currently broken. So I have to wait for fixing it. Than I will implement it.

**Comment by artemanufrij** [comment]
Was shipped with last version. (is currently waiting for human testing)
