### ISSUE TITLE
Remember Window size on close

### ISSUE THREAD

**Issue by arshubham** [artemanufrij/webpin#17]
Each webapp should remember it's window size when last opened.

**Comment by artemanufrij** [comment]
webpin saves size information already in `.desktop` file:
here is an example:
```
WebpinThemeColor=#24292e
WebpinWindowWidth=1253
WebpinWindowHeight=1272
```

**Comment by arshubham** [comment]
I maximized the current window in the web app and then closed it, but its is still opening it in the original size. Does it also update on every close?

**Comment by artemanufrij** [comment]
ah.. ok.. I guess I have to save additionaly window state...

**Comment by artemanufrij** [comment]
@arshubham can be tested

**Comment by arshubham** [comment]
It works perfectly. Thanks.

**Comment by artemanufrij** [comment]
Thank you @arshubham !
