### ISSUE TITLE
Support for whatsapp web

### ISSUE THREAD

**Issue by jvalle3** [artemanufrij/webpin#19]
Is there any way to make webpin work with https://web.whatsapp.com/??

**Comment by artemanufrij** [comment]
@jvalle3 it was already discussed in #9 ... WhatsApp doesn't support browsers based on webkit.

**Comment by artemanufrij** [comment]
Try to open web.whatsapp.com in Epiphany... It has same issue :(

**Comment by arshubham** [comment]
User agent be changed in epiphany. 
https://askubuntu.com/questions/472861/how-to-change-the-user-agent-in-gnome-web-epiphany#488555
Can't a similar solution work in this case.

**Comment by artemanufrij** [comment]
@arshubham I've tested it already, but it the response: ?missing=**cryptoSha256**,**cryptoAesCbc** in the url

**Comment by janxkoci** [comment]
see my https://github.com/artemanufrij/webpin/issues/9#issuecomment-559457913, and it also works for me in Epiphany (I tried with `snap` version 3.32, I can also try default 3.28 later at home)
