### ISSUE TITLE
Not working with certain URL

### ISSUE THREAD

**Issue by jvalle3** [artemanufrij/webpin#20]
I tried to use webpin to create a launcher for the url: 
https://calendar.google.com/calendar/render#main_7%7Cmonth
And then tried to launch the generated launcher from the menu or from Plank, with no result.
Surprisingly, it works well when i open webpin and launch the website from there.

**Comment by jvalle3** [comment]
I was testing and any url with the % character has the same issue

**Comment by artemanufrij** [comment]
@jvalle3 could you test current master branch, please? You should recreate affected webapp in webpin

**Comment by artemanufrij** [comment]
Fix is already released :)
