### ISSUE TITLE
Support favicons of web-pages

### ISSUE THREAD

**Issue by ruslankonev** [artemanufrij/webpin#22]
for make different apps

**Comment by artemanufrij** [comment]
@ruslankonev could you test current master branch please?

**Comment by ruslankonev** [comment]
Yes, now app show icon, but low res. As example — https://bitcoinnews.blog. It is possible parse available icons and set hi-res icon?

**Comment by artemanufrij** [comment]
@ruslankonev thanks for feedback. I will check it out

**Comment by artemanufrij** [comment]
@ruslankonev could you test current master branch, please?

**Comment by artemanufrij** [comment]
![bildschirmfoto von 2018-02-05 19 49 42](https://user-images.githubusercontent.com/16517095/35822898-05129704-0aae-11e8-971c-90692ac29237.png)

**Comment by ruslankonev** [comment]
@artemanufrij, that strange, but I got the same — low-res:
![image](https://user-images.githubusercontent.com/2588730/35859339-b4d52ccc-0b50-11e8-899e-8b61de28b592.png)

**Comment by artemanufrij** [comment]
@ruslankonev fix was not released yet. You can test it directly from github. You should build it manually.

**Comment by ruslankonev** [comment]
Ah, ok! yes, now it's work

**Comment by artemanufrij** [comment]
thanks you for your feedback. I'm going to close this issue and release new Version in the next few days.
