### ISSUE TITLE
Icons in wingpanel not found?

### ISSUE THREAD

**Issue by peteruithoven** [artemanufrij/webpin#23]
Awesome app! 
One minor issue, the icons I selected aren't showing up in my applications-menu. 
![screenshot from 2017-08-15 09 47 39](https://user-images.githubusercontent.com/523210/29306701-174244f8-819f-11e7-8be9-55e553bcc515.png)
They work perfectly in Plank:
![screenshot from 2017-08-15 09 50 11](https://user-images.githubusercontent.com/523210/29306717-245040f0-819f-11e7-99ea-bde1a872b02f.png)

I've previous had them located in my `~/Downloads` folder, I now moved them to `/usr/share/pixmaps/nextcloud/`, like `/usr/share/pixmaps/nextcloud/files.png` for example. But that doesn't seem to help.

Example of a file I use as icon: 
![calendar](https://user-images.githubusercontent.com/523210/29306792-6de42ce0-819f-11e7-85bc-e9952d393fff.png)

Do you have any pointers?

Having it automatically use favicons (See https://github.com/artemanufrij/webpin/issues/22) or something like that would be even greater.

**Comment by artemanufrij** [comment]
@peteruithoven Thank you for your support! 

I'm going to close this issue because it's not a webpin issue. But I've already pulled a request for fixing this behavior in "application-menu" here: https://github.com/elementary/applications-menu/pull/37

**Comment by peteruithoven** [comment]
Great! Thanks for looking into it so quickly.

**Comment by peteruithoven** [comment]
Looks like this has been fixed:
![screenshot from 2017-10-15 03-56-07](https://user-images.githubusercontent.com/523210/31580910-1ccee1fe-b15d-11e7-931c-70b31c5423ad.png)
![screenshot from 2017-10-15 03-56-37](https://user-images.githubusercontent.com/523210/31580911-1d203680-b15d-11e7-8a6a-4c8c7bde76f0.png)
