### ISSUE TITLE
Zoom support

### ISSUE THREAD

**Issue by pamarsan** [artemanufrij/webpin#27]
Hey! I really like this app, but I miss one feature: zoom support. Would it be posible to implement some kind of "ctrl++ or ctrl+-" zoom control and make each individual webapp to remember its own default zoom level? Thank you very much!

**Comment by artemanufrij** [comment]
@pamarsan could you test current master branch, please? ctrl+0 reset zoom factor

**Comment by pamarsan** [comment]
Agh sorry not using currently eOS on my machine (i just remembered it and opened this issue) so cannot help in that. Sorry mate 😬
