### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rstreeter** [artemanufrij/webpin#28]
I was wondering if it is possible to make a build for systems other than Elementary. I was wanting to build a debian package or just build and install it. If this is possible it would be awesome to know how.

Thank you

**Comment by artemanufrij** [comment]
clone this repository:
`git clone https://github.com/artemanufrij/webpin.git`
`cd webpin`
Make a build folder
`mkdir build`
`cd build`
if some packages have an error... install it
`cmake -DCMAKE_INSTALL_PREFIX=/usr ..`
`make`
install it on your system
`sudo make install`
