### ISSUE TITLE
Create webapps with firefox

### ISSUE THREAD

**Issue by arshubham** [artemanufrij/webpin#31]
Just like ICE from peppermint os gives option to create apps from with firefox and chrome 

https://github.com/peppermintos/ice

https://github.com/peppermintos/ice/blob/master/usr/bin/ice-firefox

**Comment by cassidyjames** [comment]
This wouldn't allow the app to do its handy features like controlling the titlebar, running in the background, having a copy link feature, etc. I don't think it makes sense for this app.

**Comment by artemanufrij** [comment]
aggree with @cassidyjames

**Comment by arshubham** [comment]
@artemanufrij I understand. Thanks for consideration. Maybe someday firefox will implement something similar.
