### ISSUE TITLE
Pin icon missing?

### ISSUE THREAD

**Issue by peteruithoven** [artemanufrij/webpin#32]
I understand from [this](https://github.com/artemanufrij/webpin/issues/26#issuecomment-326817788) comment there should be a pin icon here: 
![screenshot from 2017-09-07 10 56 52](https://user-images.githubusercontent.com/523210/30154932-bebb5e80-93bb-11e7-999c-1fcf95113218.png)

Anything I can do to track down what might be going wrong? 

I'm running Webpin 0.1.7 on Elementary OS Loki

**Comment by apcamargo** [comment]
I'm getting the same problem

**Comment by artemanufrij** [comment]
could you check pls, if you have `view-pin-symbolic.svg` in `/usr/share/icons/elementary/actions/symbolic/`?

![screenshot from 2017-09-07 21 03 55](https://user-images.githubusercontent.com/16517095/30180429-2cd92e16-9410-11e7-99b3-8666ed2dd76e.png)

**Comment by apcamargo** [comment]
I don't have it

**Comment by artemanufrij** [comment]
Hm... It's a system icon :confused:

**Comment by artemanufrij** [comment]
Oh.. I see. It was added 2 month ago. Actual it exists only on daily repo. :confused:

**Comment by artemanufrij** [comment]
https://github.com/elementary/icons/commits/master/actions/symbolic/view-pin-symbolic.svg

**Comment by artemanufrij** [comment]
Newst icon set was shipped today

![bildschirmfoto von 2017-10-05 18 59 45](https://user-images.githubusercontent.com/16517095/31240008-63722fea-a9ff-11e7-8483-e8d0d9c9a62e.png)
