### ISSUE TITLE
Multiple Notification

### ISSUE THREAD

**Issue by arshubham** [artemanufrij/webpin#34]
When using telegram with webpin. For every message I get, two notifications -- One from telegram and one from webpin. There should be options to block notifications from webpin as well as block notifications all together for a webapp.

**Comment by artemanufrij** [comment]
@arshubham could you check current master branch, please? I've added a mute option:
![mute](https://user-images.githubusercontent.com/16517095/30178027-e7b14f74-9407-11e7-9fdb-eead7cc1538f.png)

**Comment by arshubham** [comment]
It works perfectly! On a side note shouldn't the mute option be enabled by default as the webapps which need notifications simply ask for them.

**Comment by artemanufrij** [comment]
@arshubham I think we shoud remove "mute" option from webpin. It makes no sence to enable/disable it in the application (Slack/Telegram/etc) and additionaly in webpin.

**Comment by artemanufrij** [comment]
already merged into master branch
