### ISSUE TITLE
Allow setting custom headerbar color per-webapp

### ISSUE THREAD

**Issue by grvrulz** [artemanufrij/webpin#43]
This will really help with having these apps integrate with the browser shell. The colors can either be picked from a pre-determined pallette, or from the web-app's page(or just any custom color).

**Comment by cassidyjames** [comment]
As a default, it could pick up the meta theme color https://developers.google.com/web/fundamentals/design-and-ux/browser-customization/#meta_theme_color_for_chrome_and_opera

**Comment by artemanufrij** [comment]
@grvrulz  could you test current master branch please? I should be installed before starting. As first I added a button in the edit view.
![bildschirmfoto von 2017-11-08 23 12 03](https://user-images.githubusercontent.com/16517095/32577569-a80ae9c6-c4da-11e7-9cfa-7097def493a3.png)

**Comment by grvrulz** [comment]
@artemanufrij The colors work great :)

The next step might be to calculate the contrast, and switch to white text and icons in the headebar. Please also consider fetching the meta theme color as suggested by @cassidyjames .

**Comment by artemanufrij** [comment]
@cassidyjames I don't found any website which uses `apple-mobile-web-app-status-bar-style` or `theme-color` (in desktop mode). tested: youtube, github etc.

**Comment by artemanufrij** [comment]
@grvrulz current master branch has implemented `theme-color`. could you test it please?

**Comment by artemanufrij** [comment]
I'm going to close this issue. `them-color` was implemented into current master branch.
