### ISSUE TITLE
High CPU use (webkitprocess)

### ISSUE THREAD

**Issue by jos-henson** [artemanufrij/webpin#47]
Hi there, first of all, I absolutely love this app, is even better than the Freya app Webby which I missed for a long time until this came along!

Unfortunately, recently I have had some issues with the app using very high levels of my CPU, which kicks in the fan on my laptop every 30 seconds or so.

Specifically, after running TOP the process responsible is Webkitprocess (screenshot attached).

I have tried purging the app and reinstalling it, as well as clearing all the config files, trying different websites etc, but the problem persists.

The CPU only spikes immediately once I actually launch any webapp (e.g. not just from webpin itself) which makes sense as it is the webkitprocess that is going crazy.

Any ideas on what this might be? I realise it may very likely be an issue with Webkit itself, but what is strange is I never noticed it until quite recently, and definitely would have because of the fan usage and the loud noises it makes...which is impossible to miss given that I have been using a webapp constantly when my computer is on ever since webpin was launched as I use it for my web-based email service.

Many thanks in advance and please let me know what logs/information I can provide that will help to hopefully resolve this.

Jos
![screenshot from 2017-11-08 19 02 12](https://user-images.githubusercontent.com/20843349/32565558-610e2e3e-c4b7-11e7-955d-7fd0c245fc54.png)

**Comment by jos-henson** [comment]
Thanks for agreeing to look into this. I'm running Webpin on multiple machines and use it for multiple different websites, so if there is any additional infromation or debug logs I can provide that would be helpful please let me know.

Would it be helpful to also file a bug with Webkit?

**Comment by artemanufrij** [comment]
can't reproduce it (on loki) anymore

**Comment by AlexDerbenew** [comment]
Issue is relevant today. Detected high CPU usage while using https://harvestapp.com in Webpin
![Снимок экрана от 2020-05-12 16-56-28](https://user-images.githubusercontent.com/39634495/81700624-9299f500-9471-11ea-881f-0d87b2874cc4.png)
