### ISSUE TITLE
Desktop Icon's parameters not used

### ISSUE THREAD

**Issue by guilmour-asc** [artemanufrij/webpin#48]
Hello. I'd like to inform an issue.

I think the Webpin parameters (on the desktop icon) are not being used. The GIF illustrates that...

![peek 15-11-2017 12-19](https://user-images.githubusercontent.com/26415345/32840837-f24505ba-c9ff-11e7-8042-4bdfbec12a56.gif)

I still don't know if this problem occurs with someone else, beyondme, you know...
Thanks for the attention.

**Comment by guilmour-asc** [comment]
Hey, sup. It works, now... :smile:

**Comment by artemanufrij** [comment]
@guilmour-asc thank you for your feedback!
