### ISSUE TITLE
Fetch the iOS icon

### ISSUE THREAD

**Issue by apcamargo** [artemanufrij/webpin#56]
Many websites provide a high resolution icon intended to be used in iOS. It would be useful if Webpin could get these icons automatically.

https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by LunkRat** [comment]
+1

**Comment by artemanufrij** [comment]
@apcamargo , @LunkRat  if you want, you can test current master branch. I just implemented this function

**Comment by artemanufrij** [comment]
Icon fetching was implemented and released
