### ISSUE TITLE
Support for back/forward keys (typically mouse button 4/5)

### ISSUE THREAD

**Issue by jlnr** [artemanufrij/webpin#58]
This app is great :) Thanks! valadoc.org looks fantastic in it.

Feature request: Most elementary apps can be navigated with mouse buttons or keys that are mapped to [XF86Back and XF86Forward](http://wiki.linuxquestions.org/wiki/XF86_keyboard_symbols). It would be great if this also worked in apps created using Webpin.

**Comment by artemanufrij** [comment]
@jlnr currently you can do that by press <ALT> + LEFT/RIGHT. But I think your suggestion is very useful. Give me a moment :+1:

**Comment by artemanufrij** [comment]
@jlnr in my case they are 8/9

**Comment by artemanufrij** [comment]
@jlnr could you test current master branch please?

**Comment by jlnr** [comment]
Wow, that was quick :) Right now `mkdir build && cd build && cmake ..` is choking on this:

```
CMake Error at CMakeLists.txt:27 (include):
  include could not find load file:

    ValaPrecompile


CMake Error at CMakeLists.txt:28 (find_package):
```

Will try to work around this by setting env vars...

**Comment by jlnr** [comment]
Back works, forward doesn't.

**Comment by jlnr** [comment]
I've just looked at the source code and I wonder if my mouse is to blame. I had to remap my fifth mouse button to XF86Forward because by default it is mapped to something silly. This mapping works fine throughout elementaryOS, including Epiphany, but maybe it's throwing off the JavaScript button numbers?

**Comment by artemanufrij** [comment]
@jlnr I don't know... I use some Logitech and Dell mouse devices without modifying it. And it works fine in all browsers and other apps like `Files`. :man_shrugging:

**Comment by jlnr** [comment]
Ah, got it. Mice usually send button 8/9. However, there are also Gdk *key* constants for Back/Forward navigation (I assume for [monstrosities like this](http://www.dansdata.com/images/globlink/multimedia_fn_1280.jpg)), and that's what I've mapped my mouse button to.

So if I add this in addition to the button_press handler, everything works for me:

```vala
            web_view.key_press_event.connect ((event) => {
                if (event.keyval == Gdk.Key.Back) {
                    web_view.go_back ();
                    return true;
                } else if (event.keyval == Gdk.Key.Forward) {
                    web_view.go_forward ();
                    return true;
                }
                return base.key_press_event (event);
            });
```

Obviously I should also reconsider the way I mapped my mouse button :sweat_smile:, but since the rest of elementary understands the navigation Gdk.Keys, I would still suggest adding the above code.

**Comment by artemanufrij** [comment]
let me try it...

**Comment by artemanufrij** [comment]
@jlnr `Gdk.Key.Back` doesn't work. Its value is 269025062 :confused:

**Comment by jlnr** [comment]
Yes, I had to set the key_press_event handler in addition to button_press_event (from your commit).

**Comment by artemanufrij** [comment]
I see.. good point! I pushed it into current master

**Comment by jlnr** [comment]
Great, thanks!

**Comment by artemanufrij** [comment]
@jlnr thank you for your support! New release is waiting for approve...
