### ISSUE TITLE
Support Webgl

### ISSUE THREAD

**Issue by harisvsulaiman** [artemanufrij/webpin#60]
Hi, @artemanufrij 
Great work on webin BTW, I ran into an issue running figma as a webpin app.
It seems like webkit under the hood of webpin does not have webgl enabled by default, Is there a way to enable it or if it's supported.

![image](https://user-images.githubusercontent.com/29329325/36076599-5dfd2cfa-0f84-11e8-9a61-2a1deff7744e.png)

**Comment by artemanufrij** [comment]
@harisvsulaiman let me take a look

**Comment by artemanufrij** [comment]
@harisvsulaiman could you check current master branch?

**Comment by artemanufrij** [comment]
just tested it wit a game and it works:
![bildschirmfoto von 2018-02-11 20 51 35](https://user-images.githubusercontent.com/16517095/36077618-6c257786-0f6d-11e8-956d-fcddeda3f0a1.png)

**Comment by harisvsulaiman** [comment]
@artemanufrij Unfortunately webkit or chrome doesn't detect my settings. But i can enable webgl in chrome forcefully and it works beautifully.

This was not an issue at your end.
Thanks BTW,

**Comment by harisvsulaiman** [comment]
It seems like like webgl gets turned off sometimes. i can now get figma working but the view is blacked out
![image](https://user-images.githubusercontent.com/29329325/36271655-4135f39e-12a5-11e8-9e8a-b558429bbf81.png)

Can you try out figma.com?

**Comment by artemanufrij** [comment]
@harisvsulaiman will do...

**Comment by artemanufrij** [comment]
@harisvsulaiman I can't sing in. it opens always external browser window :confused:

**Comment by harisvsulaiman** [comment]
Hi @artemanufrij
Try signing in using username and password

**Comment by artemanufrij** [comment]
@harisvsulaiman it looks like a webkit bug. epiphany can't also show it:
![bildschirmfoto von 2018-02-20 21 19 03](https://user-images.githubusercontent.com/16517095/36447223-f9c10048-1683-11e8-92ac-1fbb9364995f.png)

**Comment by harisvsulaiman** [comment]
@artemanufrij updated WebKit?

**Comment by artemanufrij** [comment]
@harisvsulaiman current one in elementary repos (0.4.1 stable)

**Comment by artemanufrij** [comment]
@harisvsulaiman I think I can't fix it. It looks like a WeKit bug. I tested it on JUNO and it also doesn't work.

**Comment by harisvsulaiman** [comment]
Ok, Maybe fixed in the next release of WebKit.

**Comment by artemanufrij** [comment]
I hope so. I'm going to close this issue because I can't fix it.
