### ISSUE TITLE
Ability to spoof agent header

### ISSUE THREAD

**Issue by joedborg** [artemanufrij/webpin#62]
Hey all,

I think this would be a good feature as sites like Whatsapp don't work - they just ask you to go download Chrome, Firefox, Edge etc.

Thanks,
Joe

**Comment by grvrulz** [comment]
This can also be helpful for opening things with a mobile user agent.(e.g. Instagram or similar)

**Comment by artemanufrij** [comment]
Will check it tonight :+1:

**Comment by artemanufrij** [comment]
@joedborg @grvrulz I changed useragent `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/64.0.3282.140 Chrome/64.0.3282.140 Safari/537.36` but whatsapp doesn't work yet

**Comment by artemanufrij** [comment]
![bildschirmfoto von 2018-02-20 19 13 08](https://user-images.githubusercontent.com/16517095/36441189-27f29be6-1672-11e8-88cb-8a567e341ffc.png)

**Comment by artemanufrij** [comment]
I found this tweet about WA:
https://twitter.com/gnomeweb/status/900727025937383424?lang=de

**Comment by artemanufrij** [comment]
hey guys, WhatsApp (as example) works on JUNO. I'm going to close it because I can't fix it on LOKI

![bildschirmfoto von 2018-03-19 22 30 57](https://user-images.githubusercontent.com/16517095/37623550-606165da-2bc5-11e8-9795-5bfbe89a79d1.png)

**Comment by soham2008xyz** [comment]
@artemanufrij What is the issue you are facing on eOS Loki?

**Comment by artemanufrij** [comment]
It uses old webkit version

**Comment by SiDevesh** [comment]
@artemanufrij can we allow the user to select the user agent while creating the web app ?
Certain apps disallow certain features based in user agent, for example,
Instagram supports direct messages on mobile but not on desktop.
We can add a dropdown or just a toggle to use mobile version in Create new web app dialog.
Let me know if you are interested, would love to help out in implementing this :)
