### ISSUE TITLE
Figma

### ISSUE THREAD

**Issue by Ice-Cat** [artemanufrij/webpin#67]
I added a Figma app. But this web application refuses to work in Webpin.
![2018-03-27 18-11-00](https://user-images.githubusercontent.com/26859443/37976484-466c281a-31ea-11e8-8799-eaf5e84d04e6.png)
![2018-03-27 18-10-13](https://user-images.githubusercontent.com/26859443/37976485-469319f2-31ea-11e8-8e53-bf075fa587ae.png)
Thank you in advance

**Comment by artemanufrij** [comment]
@Ice-Cat thank you for your feedback. But I can't fix it. Webpin uses webkit and webkit can't open Figma web site. Epiphani can't also open it. I hope it will be fixed in next webkit version.
