### ISSUE TITLE
Opening again after "run in background if closed" puts window in centre of screen

### ISSUE THREAD

**Issue by bgcarlisle** [artemanufrij/webpin#69]
To reproduce error:

* Add app to dock
* Open web app
* Place where you want it on your screen (not in the centre)
* Click "Run in background if closed"
* Close window
* Click app icon in dock

The window is no longer where you left it. It has been centred.

**Comment by bgcarlisle** [comment]
Obligatory comment on issue number:

NICE

**Comment by artemanufrij** [comment]
@bgcarlisle should be fixed in current master branch. could you test it please?

**Comment by bgcarlisle** [comment]
No, sorry, I don't know how to do that

**Comment by artemanufrij** [comment]
Hm...ok... let me test it more intensive. I will push a new release in next few days

**Comment by bgcarlisle** [comment]
Works perfectly now! Thanks so much! :D

**Comment by artemanufrij** [comment]
@bgcarlisle you are welcome
