### ISSUE TITLE
Browser buttons

### ISSUE THREAD

**Issue by giovannicaligaris** [artemanufrij/webpin#78]
This is just a wish.

When setting up your new webpin, to have the option to have browser buttons such as back/forward and reload.

**Comment by artemanufrij** [comment]
@giovannicaligaris it has some hotkeys for this behavior:
F5 / Ctrl+F5 for reload
Alt+Left/Right for navigation back and forward

**Comment by artemanufrij** [comment]
something like this?
![screenshot von 2018-10-26 19 41 08](https://user-images.githubusercontent.com/16517095/47583268-39ce3e80-d957-11e8-88e5-6748d10a2f78.png)
