### ISSUE TITLE
Notifications?

### ISSUE THREAD

**Issue by Hedronmx** [artemanufrij/webpin#8]
Is it possibly to get notification support?

**Comment by artemanufrij** [comment]
I will check it out..

**Comment by artemanufrij** [comment]
ok, notifications are working on my dev version except the icon. Notification shows always "webpin" icon instead custom icon (desktop). Anyway, I will pull it today into master branch. I will fix it later - after holidays.

**Comment by artemanufrij** [comment]
@Hedronmx could you test curren master branch please?

**Comment by Hedronmx** [comment]
Sure thing! Notifications seem to work. The only thing missing is the custom icon, which you already stated. >:D

**Comment by Hedronmx** [comment]
Sorry for double post.
The app keeps asking for notification access everytime I close the app. If I open the app I grant notification access on the website (www.getflow.com) I get notifications, next time i open the app I need to grant the notification access again, if not, no notifications appear.

**Comment by artemanufrij** [comment]
Could you test this site with Epiphany?

**Comment by Hedronmx** [comment]
Same problem as described, need to allow access every time I re launch epipahny

**Comment by artemanufrij** [comment]
I guess it's a webkit issues...

**Comment by Hedronmx** [comment]
:/ dang webview, always ruining things! Well... Thanks!
