### ISSUE TITLE
Cannot use custom icon for trello.com

### ISSUE THREAD

**Issue by jlnr** [artemanufrij/webpin#80]
I've created an app for Trello, but the default icon looks really bad in the dock (huge black favicon).

Then I've deleted the app and created a new one, but my PNG icon is always overridden by the black favicon.

The PNG file does not seem to be the issue, because I just tried creating an app for another domain with this icon, and it worked.

**Comment by artemanufrij** [comment]
hey @jlnr what happens, if you edit the app and change the icon?

**Comment by jlnr** [comment]
Ah, I didn't notice that option. It works when I change the icon after the fact.

By the way, is it my responsibility to keep the PNG files around after create the web app? I had moved  them to the trash and now my web app in the dock has an empty placeholder icon.

**Comment by artemanufrij** [comment]
If you choose an icon, the app saves just the path. It doesn't copy it to an other place.

PS: I fixed this issue

**Comment by artemanufrij** [comment]
@jlnr feel free to open an issue. I will fix it...
