### ISSUE TITLE
Save custom icons so the user doesn't have to

### ISSUE THREAD

**Issue by jlnr** [artemanufrij/webpin#81]
From 
https://github.com/artemanufrij/webpin/issues/80#issuecomment-434433591:

Right now the user is responsible for keeping custom icon files around. It would be more convenient if Webpin could create a copy of these files.

**Comment by artemanufrij** [comment]
hey @jlnr could you test current master branch?

**Comment by jlnr** [comment]
Seems to work: I've trashed the icon file, rebooted the machine, and the pinned site still has its dock icon. Thanks!
