### ISSUE TITLE
Make extra controls optional

### ISSUE THREAD

**Issue by cassidyjames** [artemanufrij/webpin#82]
A lot of well-designed web apps work well without having extra chrome like back, forward, home, reload, and copy URL buttons. It might be useful to have a "minimal UI" toggle or something when creating/editing a web app to hide those controls for a more integrated look.

**Comment by artemanufrij** [comment]
Added new option
![screenshot von 2018-11-03 15 41 16](https://user-images.githubusercontent.com/16517095/47953502-ea06fd00-df7e-11e8-9e21-3b270fbda9a6.png)
