### ISSUE TITLE
Whatsapp Web support

### ISSUE THREAD

**Issue by giovannicaligaris** [artemanufrij/webpin#9]
I love Webpin but I would like to know if there could be support for whatsapp? 

Right now it doesn't work because Webpin builds webapps with Epiphany (or maybe I am wrong).

**Comment by artemanufrij** [comment]
@giovannicaligaris thank you for your request. Webpin uses webkit (epiphany uses also webkit).

What url are you using for Whatsapp?

**Comment by giovannicaligaris** [comment]
https://web.whatsapp.com

**Comment by artemanufrij** [comment]
@giovannicaligaris by the way telegram works very well:
https://web.telegram.org/

**Comment by giovannicaligaris** [comment]
Yes it does. I tried all of them, Skype web, Spotify Web, Hangouts Web... All of them work well and looks really nice, it's just Whatsapp that doesn't work.

**Comment by artemanufrij** [comment]
I'm sorry. I guess I can't help you :(

It looks like WhatsUp doesn't support webkit browsers
![bildschirmfoto von 2017-08-08 22 08 21](https://user-images.githubusercontent.com/16517095/29092272-1ef4123a-7c86-11e7-9c91-aeded34bb744.png)

**Comment by giovannicaligaris** [comment]
Oh well

**Comment by janxkoci** [comment]
Strange, for me it shows no such message (btw Safari is *the* webkit browser). Instead it just loads the QR code indefinitely.

**Comment by janxkoci** [comment]
Here is what I see:

### Webpin
![Snímek z 2019-11-28 18-39-56](https://user-images.githubusercontent.com/19331850/69825380-5f3f1300-120f-11ea-92ad-b2cfa704ca21.png)

### Epiphany 3.28 (default)
![Snímek z 2019-11-28 18-41-00](https://user-images.githubusercontent.com/19331850/69825397-6fef8900-120f-11ea-8fbe-e6cddf1a523e.png)

### Epiphany 3.32 (snap)
![Snímek z 2019-11-28 18-42-17](https://user-images.githubusercontent.com/19331850/69825421-8695e000-120f-11ea-8839-1adab1a22a36.png)

The loading animations in the first two cases just keep spinning forever, while in Ephy 3.32 it loads the code within a second or so. Epiphany 3.32 from snap uses Webkit 2.24.2, which is similar to the normal default Ephy (that one should be 2.24.4).

**Comment by janxkoci** [comment]
I've found a bug report for webkit, but I cannot login for some reason: https://bugs.webkit.org/show_bug.cgi?id=203404

**Comment by mcatanzaro** [comment]
> I'm sorry. I guess I can't help you :(
> 
> It looks like WhatsUp doesn't support webkit browsers

Many years ago, I added a user agent quirk to WebKit to make sure Whatsapp always receives a user agent imitating Safari. (Whatsapp has lost the right to receive an accurate user agent from WebKit.) That quirk actually predates your comment here. My guess is that elementary OS was shipping a very old version of WebKit at the time you left your comment. It's also possible that you have manually disabled the enable-site-specific-quirks setting of WebKitSettings. Whatsapp will not load if this setting is disabled.

**Comment by janxkoci** [comment]
Btw it works for me now:

![Snímek z 2020-02-23 18-14-25](https://user-images.githubusercontent.com/19331850/75116409-5f14af00-5668-11ea-8a8a-033a7c5feb91.png)

I guess some webkit update fixed it.

Consider closing..

**Comment by mcatanzaro** [comment]
This was fixed in https://trac.webkit.org/changeset/255233/webkit.

**Comment by mcatanzaro** [comment]
> This was fixed in https://trac.webkit.org/changeset/255233/webkit.

(This was also totally different from the original bug report here, which predates the WebSockets regression by a lot.)

**Comment by rajkumaar23** [comment]
A strange issue I'm facing is that, everytime I reopen WhatsApp webapp, it shows me an alert to "Turn on Desktop Notifications" eventhough I click Turn On everytime.

![image](https://user-images.githubusercontent.com/37476886/89175476-7b1c6500-d5a5-11ea-9c71-54a607d42016.png)
